### ISSUE TITLE
Confusion about the completeness of the dataset

### ISSUE THREAD

**Issue by promiti-dasgupta** [dfsp-spirit/abide_preproc_smri_freesurfer6#1]
Hi there, I was looking at the dataset in this repository and I'm a bit confused about whether this is a subset of the full dataset or the entire dataset. Could you please clarify this for me? I'm interested in using this FreeSurfer preprocessed structural MRI dataset for my research and it would be helpful to know if it's complete. If it's not complete, could you please provide me the full dataset? I would be very grateful for this. Thank you!

**Comment by dfsp-spirit** [comment]
Hi antu10704,

This data is the FreeSurfer output for all 1035 subjects of the ABIDE I dataset.

For each subject, the data is not the full output of FreeSurfer, e.g., log files and other parts of the output which are typically not relevant have not been uploaded.

I would suggest you have a look at the files for one subject, and if you feel you need files which are not included, let me know so I can upload them. Please make sure to list all missing files you need, with exact filenames, based on the `subjects_dir/subject/`directory. E.g.:

```
* surf/lh.pial
* surf/rh.pial
* label/lh.cortex.label
* label/rh.cortex.label
```

An upload takes some work, so please make sure you really list **all** files you need, so I do not need to start a 2nd upload later because a file is missing.

I have added information to the README to reduce the confusion of others. Thanks for opening this issue!

**Comment by dfsp-spirit** [comment]
@antu1704 Does this answer your question? I am closing this for now, feel free to post another issue if you need certain files which are currently missing.
