### ISSUE TITLE
Request for Destrieux Atlas Parcellated Stats

### ISSUE THREAD

**Issue by promiti-dasgupta** [dfsp-spirit/abide_preproc_smri_freesurfer6#2]
Hi, can you provide the aparc stats (Destrieux atlas : thickness, area, volume) data like you provided for Desikan atlas in a stats directory ? It would be very helpful for me.
Thanks.

**Comment by dfsp-spirit** [comment]
Yes, I can do that. I am currently on holidays though, and I will only have access to the data when I am back home, which will not be before June 22nd.

**Comment by promiti-dasgupta** [comment]
Many Thanks! 
Can you confirm me about the nature of the dataset?
In the /stats/aseg_table.tsv there are values for volume of different subcortical structures (which is for volume based analysis) and in the /stats/lh.aparc_table_area.tsv, /lh.aparc_table_thickness.tsv and lh.aparc_table_volume.tsv, there are values for cortical areas(mm2) , thickness(mm) volume(mm3) for cerebral cortex regions of interest parcellated by Desikan-Killinany Atlas (which is used for surface-based analysis) ?
I want to use this dataset for predicting autism but i need to see how to manipulate this data in deep learning models to do so. Can you give me some ideas or any paper related to this data?
Really thanks for your time.

**Comment by dfsp-spirit** [comment]
> Can you confirm me about the nature of the dataset? In the /stats/aseg_table.tsv there are values for volume of different subcortical structures (which is for volume based analysis) and in the /stats/lh.aparc_table_area.tsv, /lh.aparc_table_thickness.tsv and lh.aparc_table_volume.tsv, there are values for cortical areas(mm2) , thickness(mm) volume(mm3) for cerebral cortex regions of interest parcellated by Desikan-Killinany Atlas (which is used for surface-based analysis) ?

Yes, in FreeSurfer speech, a segmentation (`aseg`) is volume based, and a parcellation (`aparc`) is surface (mesh) based.

> I want to use this dataset for predicting autism but i need to see how to manipulate this data in deep learning models to do so. Can you give me some ideas or any paper related to this data? Really thanks for your time.

As a neuroscientist, I can tell you that most likely everyone in the field has tried this already on the ABIDE dataset. 

Still, if you want to do ML to predict autism purely from structural images, have a look at the effect sizes reported even for group comparisons in typical papers to make sure your expectations align with reality. That being said, I have written a Python package that gathers as much information as possible from FreeSurfer output in a nice table for deep learning (because the *everyone in the field* mentioned above includes me, of course). It is here: [braindescriptors.py in the brainload package](https://github.com/dfsp-spirit/brainload/blob/master/src/brainload/braindescriptors.py). That package is mainly for my own use and not a published package according to my standards on documentation, but it may save you a lot of time. Basically you throw it at a recon-all output dir, tell it which files to parse, and use the `Braindescriptors.save()` function in the end to export everything to a CSV file, which you slurp into tf/torch/whatever.

**Comment by dfsp-spirit** [comment]
> Hi, can you provide the aparc stats (Destrieux atlas : thickness, area, volume) data like you provided for Desikan atlas in a stats directory ? It would be very helpful for me. Thanks.

@antu1704 I just noticed that you want Destrieux stats, not the Destrieux parcellations. FreeSurfer does not write these stat files by default for the Destrieux atlas, that is why they are not included and I do not have them. You should be able to compute them yourself from the data (my script to do that for many subjects in parallel is [here](https://github.com/dfsp-spirit/freesurfer_parallel_scripts/blob/main/tools/run_anatomical_stats.bash)).

The Destrieux parcellations (not stats for them) are included in the label download, btw.

Whether you want to rely on the stats is another question, I guess you would need to compute them manually for all datasets you use, because as I said, they are not a default FS output. If you want me to compute them, I can do it, let me know.

**Comment by promiti-dasgupta** [comment]
> Yes, in FreeSurfer speech, a segmentation (`aseg`) is volume based, and a parcellation (`aparc`) is surface (mesh) based.
In the lh.aparc_table_volume.tsv file, does it contain the gray matter volume of cortical regions parcellated by Desikan atlas? I want to measure the structural connectome of cortical gray matter volume/area/thickness seperately between different cortical regions. Can i do it using the lh.aparc_table_volume/area/thickness file by converting the .tsv file into a 2D matrix that represents the similarity measure(measured using the correlation/improved sqrt-cosine formula) among regions for a particular subject?

**Comment by promiti-dasgupta** [comment]
@antu1704 I just noticed that you want Destrieux stats, not the Destrieux parcellations. FreeSurfer does not write these stat files by default for the Destrieux atlas, that is why they are not included and I do not have them. You should be able to compute them yourself from the data (my script to do that for many subjects in parallel is [here](https://github.com/dfsp-spirit/freesurfer_parallel_scripts/blob/main/tools/run_anatomical_stats.bash)).

The Destrieux parcellations (not stats for them) are included in the label download, btw.

Whether you want to rely on the stats is another question, I guess you would need to compute them manually for all datasets you use, because as I said, they are not a default FS output. If you want me to compute them, I can do it, let me know.


Yes, I actually want to compare  the results obtained from both Desikan and Destrieux atlas. To do so, I need the stats files for both atlas. Can you confirm me about this? I am a bit confused about whether these stats files I should use as the dataset.

If you compute them for me, it would be really helpful. As I don't have the software requirements that you mentioned in the readme file of the link you provided.

**Comment by promiti-dasgupta** [comment]
> As a neuroscientist, I can tell you that most likely everyone in the field has tried this already on the ABIDE dataset.
> 
> Still, if you want to do ML to predict autism purely from structural images, have a look at the effect sizes reported even for group comparisons in typical papers to make sure your expectations align with reality. That being said, I have written a Python package that gathers as much information as possible from FreeSurfer output in a nice table for deep learning (because the _everyone in the field_ mentioned above includes me, of course). It is here: [braindescriptors.py in the brainload package](https://github.com/dfsp-spirit/brainload/blob/master/src/brainload/braindescriptors.py). That package is mainly for my own use and not a published package according to my standards on documentation, but it may save you a lot of time. Basically you throw it at a recon-all output dir, tell it which files to parse, and use the `Braindescriptors.save()` function in the end to export everything to a CSV file, which you slurp into tf/torch/whatever.

My thesis is about predicting autism by combining both structural and resting state functional mri. I want to use a common deep learning model to predict autism for both structural and functional features derived from structural and functional connectomes. I have computed functional connectome by applying tangent space embedding on the preprocessed fmri time series data. Now I want to do this also for structural information. I have gone through some papers related to detecting autism from both structural and functional mri and seen that there are inconsistent results in smri experiments. I hope to improve the results by analyzing both structural and functional mri preprocessed by different atlases ( Desikan, Destrieux atlases for structural and AAL,CC200,BASC for functional) . 

Thanks for the python package link. But if you give the Destrieux atlas stats directory after computing, I hope I don't have to use this link? Actually I have a very short time for my defense and I am not so expert.

**Comment by dfsp-spirit** [comment]
@antu1704 

Okay, I see. But to get all the stats you want, one needs to compute all 3 stats for all 2070 hemispheres (1035 subjects), making this more than 6210 runs of `mris_anatomical_stats`. My 48 core machine is busy with my own work, and it's gonna take _days_ to compute these on my laptop.

I am not sure what you mean by _very short time_, but it may take a while until I can compute those stats. The stats for Desikan which are already in the repo, I computed those over some weeks whenever I found the time and compute resources.

**Comment by dfsp-spirit** [comment]
@antu1704 
Okay, I wrote multi-core version of the stats script and let it run over night on an 8 core machine. It's done and the Destrieux stats are now available in the [stats/aparc.a2009s](https://github.com/dfsp-spirit/abide_preproc_smri_freesurfer6/tree/main/stats/aparc.a2009s) directory of this repo. 

FYI, The new parallel anatomical stats script computation script can be found [here](https://github.com/dfsp-spirit/freesurfer_parallel_scripts/blob/main/tools/parallel_anatomical_stats_outer.bash), and the script for gathering the stats into tables [here](https://github.com/dfsp-spirit/freesurfer_parallel_scripts/blob/main/tools/get_stats_tables.bash).

**Comment by dfsp-spirit** [comment]
@antu1704 FYI: I have now also computed the volume of various parts of the brain using FreeSurfer tools, the results are available for all subjects in the `/stats/brainvol` directory.
